## Pytorch Basic

In [3]:
pip install torch torchvision torchaudio

     |████████████████████████████████| 108.1 MB 2.6 MB/s 
     |████████████████████████████████| 1.0 MB 318 kB/s 
     |████████████████████████████████| 1.4 MB 2.9 MB/s 
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as numpy

import torch

In [5]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
type(nums)

torch.Tensor

In [8]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [10]:
randoms = torch.rand((3,3))
randoms

tensor([[0.8595, 0.9113, 0.2282],
        [0.6913, 0.4943, 0.8212],
        [0.6439, 0.7864, 0.3813]])

In [11]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
zeros.size()

torch.Size([3, 3])

## Operations

In [15]:
# pytorch로 수학연산

In [17]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [18]:
nums = nums.reshape((3,3))

In [21]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [19]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [22]:
result = torch.add(nums, 10)

In [23]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

## View

In [24]:
range_nums = torch.arange(9).reshape(3,3)

In [25]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [26]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
range_nums.view(1,9).shape

torch.Size([1, 9])

## Slice and Index

In [29]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [30]:
nums[1]

tensor([3, 4, 5])

In [31]:
nums[1,1]

tensor(4)

In [32]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

## Compile

In [35]:
# numpy를 torch tensor로 불러오기
import numpy as np

In [36]:
arr = np.array([1,1,1])

In [37]:
arr_torch = torch.from_numpy(arr)

In [40]:
arr_torch

tensor([1, 1, 1])

In [39]:
arr_torch.float()

tensor([1., 1., 1.])

In [41]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [42]:
device

'cpu'

In [43]:
arr_torch.to(device)

tensor([1, 1, 1])

## AutoGrad

In [45]:
x = torch.ones(2,2, requires_grad =True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [46]:
y = x + 2

In [47]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [48]:
print(y.grad_fn)

In [49]:
z  = y * y * 3
out = z.mean()

In [50]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [51]:
out.backward()

In [52]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [54]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [55]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False
